<?php
/**
 * Add support for co-authors in feeds.
 *
 * @package Automattic\CoAuthorsPlus
 */

/**
 * Applies co-author bylines to feed output.
 *
 * Feed markup is generated by WordPress core (`wp-includes/feed-rss2.php` and
 * friends), not by the theme, so unlike the template filters in
 * CoAuthors_Template_Filters these hooks are safe to apply by default.
 */
class CoAuthors_Feed_Filters {

	/**
	 * Register the feed filter hooks.
	 *
	 * Called from the composition root after construction so that creating an
	 * instance has no global side effects.
	 */
	public function register_hooks(): void {
		// Priority 15 so this wins over CoAuthors_Template_Filters::filter_the_author.
		add_filter( 'the_author', array( $this, 'filter_the_author_rss' ), 15 );
		add_action( 'rss2_item', array( $this, 'action_add_rss_guest_authors' ) );
	}

	/**
	 * Replace the feed byline with the first co-author's display name.
	 *
	 * Runs only in a feed, so template output is unaffected.
	 *
	 * @param string $the_author The author name core resolved from `post_author`.
	 * @return string The first co-author's display name, or the original value.
	 */
	public function filter_the_author_rss( $the_author ) {
		if ( ! function_exists( 'coauthors' ) || ! is_feed() ) {
			return $the_author;
		}

		$coauthors = (array) get_coauthors();
		if ( count( $coauthors ) >= 1 && isset( $coauthors[0]->display_name ) ) {
			/*
			 * Core registers `add_filter( 'the_author', 'ent2ncr', 8 )`. This filter runs at
			 * 15 and replaces the string wholesale, so the replacement would otherwise never
			 * pass through that normalization. Invisible in RSS2, where the value sits inside
			 * CDATA, but feed-atom.php renders the_author() inside a bare <name> element.
			 */
			return ent2ncr( $coauthors[0]->display_name );
		}

		return $the_author;
	}

	/**
	 * Output a dc:creator element for each co-author beyond the first.
	 *
	 * The first co-author is already rendered by core's `the_author()` call, which
	 * self::filter_the_author_rss() has filtered.
	 *
	 * @return void
	 */
	public function action_add_rss_guest_authors(): void {
		$coauthors = (array) get_coauthors();

		// Remove the first co-author, who is already added to the first dc:creator element.
		array_shift( $coauthors );

		foreach ( $coauthors as $coauthor ) {
			if ( empty( $coauthor->display_name ) ) {
				continue;
			}

			/*
			 * Everything between `<![CDATA[` and `]]>` is literal, so escaping here would
			 * make a display name like "Smith & Jones" render as "Smith &amp; Jones" in
			 * feed readers. Core's feed-rss2.php does not escape inside CDATA either. The
			 * only sequence that needs guarding is the CDATA terminator itself.
			 */
			$display_name = str_replace( ']]>', ']]&gt;', $coauthor->display_name );

			echo "\t\t<dc:creator><![CDATA[" . $display_name . "]]></dc:creator>\n"; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- CDATA content is literal; see above.
		}
	}
}
